# Generated by Django 5.0.3 on 2025-04-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me_app', '0002_alter_about_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('languages', models.CharField(max_length=100)),
                ('dbms', models.CharField(max_length=100)),
                ('softwares', models.CharField(max_length=100)),
                ('others', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='about',
            name='city',
        ),
        migrations.RemoveField(
            model_name='about',
            name='country',
        ),
        migrations.RemoveField(
            model_name='about',
            name='title',
        ),
        migrations.RemoveField(
            model_name='about',
            name='varsity',
        ),
        migrations.AlterField(
            model_name='about',
            name='content',
            field=models.TextField(max_length=500),
        ),
    ]
