# Generated by Django 5.0.3 on 2025-04-18 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me_app', '0003_skills_remove_about_city_remove_about_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='cgpa',
        ),
        migrations.AddField(
            model_name='about',
            name='profession',
            field=models.CharField(default='Student', max_length=500),
        ),
        migrations.AlterField(
            model_name='about',
            name='content',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='skills',
            name='content',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='skills',
            name='dbms',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='skills',
            name='languages',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='skills',
            name='others',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='skills',
            name='softwares',
            field=models.CharField(max_length=500),
        ),
    ]
