# Generated by Django 5.0.3 on 2025-04-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me_app', '0004_remove_about_cgpa_about_profession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
