# Generated by Django 5.0.3 on 2025-04-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me_app', '0006_skills_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='profile_image',
            field=models.ImageField(default='media/eemon.jpg', upload_to='media/'),
        ),
    ]
