# Generated by Django 5.0.3 on 2025-04-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me_app', '0008_remove_about_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='content',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='content',
        ),
        migrations.AddField(
            model_name='skills',
            name='number_of_solved_problem',
            field=models.IntegerField(default=0),
        ),
    ]
