# Generated by Django 5.0.3 on 2025-04-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me_app', '0009_remove_about_content_remove_skills_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='number_of_solved_problem',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
